<?php

beforeEach(function () {
    $this->subject = new \App\Http\Requests\Settings\ProfileUpdateRequest;
});

test('rules', function () {
    $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

    $actual = $this->subject->rules();

    $this->assertValidationRules([
        'name' => [
            'required',
            'string',
            'max:255',
        ],
        'email' => [
            'required',
            'string',
            'lowercase',
            'email',
            'max:255',
        ],
    ], $actual);
});

// test cases...
