<?php

uses(RefreshDatabase::class);

test('destroy returns an ok response', function () {
    $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

    $user = \App\Models\User::factory()->create();

    $response = $this->actingAs($user)->delete(route('profile.destroy'));

    $response->assertRedirect('/');
    $this->assertModelMissing($profile);

    // TODO: perform additional assertions
});

test('edit returns an ok response', function () {
    $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

    $user = \App\Models\User::factory()->create();

    $response = $this->actingAs($user)->get(route('profile.edit'));

    $response->assertOk();

    // TODO: perform additional assertions
});

test('update validates with a form request', function () {
    $this->assertActionUsesFormRequest(
        \App\Http\Controllers\Settings\ProfileController::class,
        'update',
        \App\Http\Requests\Settings\ProfileUpdateRequest::class
    );
});

test('update returns an ok response', function () {
    $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

    $user = \App\Models\User::factory()->create();

    $response = $this->actingAs($user)->patch(route('profile.update'), [
        // TODO: send request data
    ]);

    $response->assertOk();

    // TODO: perform additional assertions
});

// test cases...
