<?php

uses(RefreshDatabase::class);

test('index returns an ok response', function () {
    $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

    $organisations = \App\Models\Organisation::factory()->times(3)->create();
    $user = \App\Models\User::factory()->create();

    $response = $this->actingAs($user)->get(route('organisations'));

    $response->assertOk();

    // TODO: perform additional assertions
});

test('show returns an ok response', function () {
    $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

    $organisation = \App\Models\Organisation::factory()->create();
    $user = \App\Models\User::factory()->create();

    $response = $this->actingAs($user)->get(route('organisation', ['id' => $organisation->id]));

    $response->assertOk();

    // TODO: perform additional assertions
});

// test cases...
